name: fast-forward
on:
  issue_comment:
    types: [created, edited]
jobs:
  fast-forward:
    if: ${{ contains(github.event.comment.body, '/fast-forward')
      && github.event.issue.pull_request }}
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Check if PR targets master
        id: check_pr_target
        uses: actions/github-script@v6
        with:
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            return pr.base.ref === 'master';

      - name: Fast forwarding
        if: ${{ steps.check_pr_target.outputs.result == 'true' && steps.check_ci_status.outputs.result == 'true' }}
        uses: sequoia-pgp/fast-forward@v1
        with:
          merge: true
          comment: 'on-error'
