name: pull-request
on:
  pull_request:
    branches: master
    types: [opened, reopened, synchronize]
jobs:
  check-fast-forward:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - name: Checking if fast forwarding is possible
        id: ff-step
        uses: sequoia-pgp/fast-forward@v1
        with:
          merge: false
          comment: 'on-error'

      - name: Log fast-forward check result
        run: echo ${{ steps.ff-step.outputs.result }}

      - name: Post comment if FF is possible
        if: steps.ff-step.outputs.result == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: "✅ you can merge to `master` branch by commenting "/fast-forward".",
            });
